version: '3.6'

services:
   mysql:
     image: mysql:5.7
     volumes:
       - ./mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: r00tP@ssw0rd
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wp_user
       MYSQL_PASSWORD: P@ssw0rd

   wordpress:
     depends_on:
       - mysql
     image: wordpress:fpm
     volumes:
      - ./wordpress:/var/www/html
     restart: always
     environment:
       WORDPRESS_DB_HOST: mysql
       WORDPRESS_DB_USER: wp_user
       WORDPRESS_DB_PASSWORD: P@ssw0rd
       WORDPRESS_DB_NAME: wordpress

   nginx:
    depends_on:
       - wordpress
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
    restart: always